### ISSUE TITLE
Masalah pada tampilan tombol mode switcher (light/dark)

### ISSUE THREAD

**Issue by ngekoding** [mazipan/mazipan.space#125]
Pada saat pertama kali membuka halaman website, mode yang aktif adalah mode light. 
Akan tetapi pada tombol mode switcher menampilkan "Switch to light ☀️".

Berikut adalah contoh tampilan yang dimaksud.

![screenshot-mazipan space](https://user-images.githubusercontent.com/11625690/107751489-6d1b7e00-6d58-11eb-8499-ef37fa452978.png)

**Comment by mazipan** [comment]
Waduh, ketahuan.
Itu fitur mas, jebakan betmen.

Hahaha, nanti lah dibenahin lagi

**Comment by ngekoding** [comment]
Oh memang disengaja mas? Hehe
Saya tadi liat postingannya di grup PHP Indonesia, dan coba-coba cek dan nemu itu.

Saya semangat aja mau bikin PR, sambil belajar Next.js, kebetulan belum pernah pakai sebelumnya. Hehe
