### ISSUE TITLE
Header not responsive at tablet size

### ISSUE THREAD

**Issue by DanielssonThomas** [mazipan/mazipan.space#153]
## Description
From about 768px < width < 890px the header doesn't have the space required for its contents. The switch theme button gets pushed out of view and the logo increases the header height, blocking part of every pages heading.

<img width="769" alt="image" src="https://github.com/mazipan/mazipan.space/assets/69715206/09b1f391-18f1-4b04-80c3-cf891fa0628b">

This would effect some tablet users

## Expected Behaviour

Header functions should stay available and responsive. 

## Additional Information

NA

**Comment by Sky-De** [comment]
@DanielssonThomas hi, i would like fix this for you,
Please assign this to me
I will start working on this as soon as i get assigned
Thanks
