### ISSUE TITLE
Beautiful Navbar

### ISSUE THREAD

**Issue by AliReza1083** [mazipan/mazipan.space#156]
## Description
The navbar needs some updates to look much better.
I also make it responsive.
![image](https://github.com/mazipan/mazipan.space/assets/99729607/7c188832-7c2f-4b48-9787-771bf6ffa727)

## Tasks

- [ ] Navbar

**Comment by r0ld3x** [comment]
@AliReza1083 assign me

**Comment by AliReza1083** [comment]
@r0ld3x 
I am not the maintainer of this repository.
