### ISSUE TITLE
Detail Post 404

### ISSUE THREAD

**Issue by nipeharefa** [mazipan/mazipan.space#157]
## Description

halo mas @mazipan detail postnya 404. Step to reproducenya: 
- dari homepage
- click salah satu post

Screenshot brave browser:
![image](https://github.com/user-attachments/assets/58a2c6b1-d977-4024-a2a2-acfe069b201a)
Edge:
<img width="1190" alt="image" src="https://github.com/user-attachments/assets/8fc61681-3835-4f2d-873a-f747771d19f1">

**Comment by mazipan** [comment]
It's up again, thank you 🤩
